<a href="https://colab.research.google.com/github/Tony01171/2501103011-p1p1/blob/main/Covid-19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
data=df=pd.read_csv('/content/country_wise_latest.csv')
sorted_by_new_cases = df.sort_values(by='New cases', ascending=False)
display(sorted_by_new_cases[['Country/Region', 'New cases', 'Confirmed', 'New deaths']].head(10))

selected_columns = df[['Country/Region', 'Confirmed']]
display(selected_columns.head())

high_confirmed_cases = df[df['Confirmed'] > 500000]
display(high_confirmed_cases[['Country/Region', 'Confirmed', 'Deaths']].sort_values(by='Confirmed', ascending=False))

sorted_by_new_cases = df.sort_values(by='New cases', ascending=False)
display(sorted_by_new_cases[['Country/Region', 'New cases', 'Confirmed', 'New deaths']].head(10))

    Country/Region  New cases  Confirmed  New deaths
173             US      56336    4290259        1076
79           India      44457    1480073         637
23          Brazil      23284    2442375         614
37        Colombia      16306     257101         508
132           Peru      13756     389717         575
154   South Africa       7096     452529         298
138         Russia       5607     816680          85
111         Mexico       4973     395489         342
6        Argentina       4890     167416         120
13      Bangladesh       2772     226225          37

  Country/Region  Confirmed
0    Afghanistan      36263
1        Albania       4880
2        Algeria      27973
3        Andorra        907
4         Angola        950

    Country/Region  Confirmed  Deaths
173             US    4290259  148011
23          Brazil    2442375   87618
79           India    1480073   33408
138         Russia     816680   13334

    Country/Region  New cases  Confirmed  New deaths
173             US      56336    4290259        1076
79           India      44457    1480073         637
23          Brazil      23284    2442375         614
37        Colombia      16306     257101         508
132           Peru      13756     389717         575
154   South Africa       7096     452529         298
138         Russia       5607     816680          85
111         Mexico       4973     395489         342
6        Argentina       4890     167416         120
13      Bangladesh       2772     226225          37